### ISSUE TITLE
Don't ask github username password multiple times

### ISSUE THREAD

**Issue by nischayv** [hammer-io/tyr#119]
The way everything is setup now, we ask github username, password, and again during one of the requests, Github requests it.

**Comment by clarkerican** [comment]
Has this been fixed? I haven't noticed the repeated request for username/password? @nischayv @jackcmeyer

**Comment by jackcmeyer** [comment]
I think that if you have the project cloned via https this might be an issue. 

However, not something we can control.

We should close this if @nischayv is cool with it
