### ISSUE TITLE
Initialize a local git repository

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/tyr#12]
As a user, I would like hammer-cli to initialize a local git repository for me. This includes creating a default README.md file and populating the .gitignore file. The .gitignore should be the industry standard gitignore for node.js projects.

How do we install git on the user's computer automatically?

- [ ] Verify local git repository is created
- [ ] Verify README.md is generated with (at minimum) the project title. Later task could handle further population of that README.md with usage instructions.
- [ ] Verify .gitignore is generated to industry standards
- [ ] Verify origin remote is generated

**Comment by nischayv** [comment]
How do we install git on the user's computer?

**Comment by KrashLeviathan** [comment]
https://www.gitignore.io/api/node

**Comment by nischayv** [comment]
https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/
