### ISSUE TITLE
Allow user to enter SKIP if app name exists on Heroku

### ISSUE THREAD

**Issue by nischayv** [hammer-io/tyr#127]
If the app name already exists on Heroku, the prompt has a loop that asks for a new name. The user can only continue the normal flow if the app creation on Heroku is successful. This feature allows the user to enter SKIP or some other keyword to continue without setting up Heroku

**Comment by jackcmeyer** [comment]
This issue is irrelevant now. We decided just to append a unique id to the end of it. Closing as won't fix.
