### ISSUE TITLE
Uncaught name format exception

### ISSUE THREAD

**Issue by NathanDeGraaf** [hammer-io/tyr#135]
https://github.com/NathanDeGraafTest/Name-must-start-with-a-letter-and-can-only-contain-lowercase-letters-numbers-and-dashes.

Result of using the name Nathan3. 

This brings up a curious point, to make sure we are in compliance with third party names.

**Comment by KrashLeviathan** [comment]
I also ran into this: 

![tyr-screenshot-error](https://user-images.githubusercontent.com/8837587/33305469-daf9b1fc-d3d3-11e7-8c47-81ec4ad7ddd3.png)

![name-must-start](https://user-images.githubusercontent.com/8837587/33305462-d0eda7b8-d3d3-11e7-958c-d992a8c11886.png)

**Comment by jackcmeyer** [comment]
This is an issue with heroku. To fix this, when we need to go to heroku we will transform the name. 

To make it compatible with heroku: 
* we will make all characters lowercase
* remove any special characters, spaces, underscores, etc to dashes (-).
