### ISSUE TITLE
Create Security Information Management Policy

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/tyr#147]
As a user, I want a Security Information Management Policy created that explicitly states the following information: 
* How usernames/password are exactly used
* What kind of information are we obtaining from third party APIs
* How they can work around not entering usernames/password

I want this Privacy Policy to be visible on the GitHub repository, NPM repository, and a URL printed at the start of the command line client. 

There should be some sort of confirmation on the CLI where the user acknowledges that they have a viewed the policy.

**Comment by KrashLeviathan** [comment]
Sounds good.

**Comment by KrashLeviathan** [comment]
The CLI confirmation piece should be handled in a separate issue though.
