### ISSUE TITLE
Fix issue where user can use / in their project name

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/tyr#148]
As a user, I want to be prevented from using / in the project name because this would not make a valid directory, it would make multiple directories.

**Comment by ChrisBrownie55** [comment]
Hey, looking for an easy first issue, could I be assigned this issue please.

**Comment by jackcmeyer** [comment]
@ChrisBrownie55 hey Chris. I've assigned this issue to you. Please checkout the Contribution Document [here](https://github.com/hammer-io/tyr/blob/master/CONTRIBUTING.md).

**Comment by jackcmeyer** [comment]
@ChrisBrownie55 Are you still interested in this issue? Otherwise I will put the help wanted flair on this issue end of day tomorrow (1/19/18).
