### ISSUE TITLE
dbConfig.json should not be pushed to GitHub

### ISSUE THREAD

**Issue by clarkerican** [hammer-io/tyr#194]
Currently, the user's username and password is pushed to GitHub along inside the dbConfig.json in the newly created project.  Could be updated to use node-config

**Comment by jackcmeyer** [comment]
As part of this issue, we should do the following: 

1. Setup node-config for the user and move the dbConfig.json file to`config/default.json`
2. Make a file `config/default-example.json` which is a blank version of the config file, which is what will get pushed to the repo. 
3. Ignore `config/default.json`
