### ISSUE TITLE
Create a File Writer Utility 

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/tyr#22]
As a user, I would like hammer-cli to use a file writer utility to write to files. This will standardize the error messages for failed file writes and reduce the amount of code.  

- [ ] Verify a file writer utility has been created and is being used

**Comment by nischayv** [comment]
Check out fs-extra. We shouldn't waste time on stuff like this. There are plenty of libraries out there that do things like this.

**Comment by jackcmeyer** [comment]
won't fix
