### ISSUE TITLE
Add ability to edit/add/remove 3rd party applications after initial config

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/tyr#71]
As a user, I would like the ability to edit/add/remove a 3rd party application after initial config. 

For example, let's say I do want any third party applications at first. A week later, I want all of them, I should be able to add them. Or the opposite, if I want to remove them. 

Note, there is a chain that is needed. 
github --> travis --> docker --> heroku. If a remove github, all of it needs to go.

**Comment by KrashLeviathan** [comment]
#112 #113 #114 #115 #116
