### ISSUE TITLE
Make npm install print out less

### ISSUE THREAD

**Issue by clarkerican** [hammer-io/tyr#91]
https://github.com/npm/npm/issues/2040

When npm Install is called, it should not print out the tree of dependencies.  
There are a couple options according to the above thread.  We can pipe the output to a file or dev/null (but idk if that is viable for windows), or we can set the depth to 0, and it will print out the tree, but it will only print out the packages in the package.json dependencies.

**Comment by thomasmeadows** [comment]
please yes for the love of god, stop spamming our CI Platforms

**Comment by jackcmeyer** [comment]
Is this still an issue. If it is, seems like low hanging fruit that we should get in to an upcoming release. 

@clarkerican
